// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.gumei.grpcservice.grpc.hello;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.netty.proto.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
